# Generated by Django 2.1.1 on 2019-02-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
    ]
