# Generated by Django 2.1.1 on 2019-02-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20190211_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
