# Generated by Django 2.1.1 on 2019-02-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_auto_20190211_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
