# Generated by Django 2.1.1 on 2019-02-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_auto_20190211_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cliente',
        ),
    ]
