# Generated by Django 2.1.1 on 2019-02-12 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190211_1943'),
        ('consultas', '0005_remove_consulta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente'),
            preserve_default=False,
        ),
    ]
