# Generated by Django 2.1.1 on 2019-02-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_endereco', models.CharField(choices=[('COMERCIAL', 'COMERCIAL'), ('RESIDENCIAL', 'RESIDENCIAL')], default='RESIDENCIAL', max_length=40)),
                ('logradouro', models.CharField(help_text='Nome da rua', max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.Cidade')),
                ('pertence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
        ),
    ]
