# Generated by Django 2.1.1 on 2019-01-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_cliente_endereco'),
        ('enderecos', '0002_endereco_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente'),
            preserve_default=False,
        ),
    ]
