# Generated by Django 2.1.1 on 2019-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0005_auto_20190210_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='tipo_endereco',
            field=models.CharField(choices=[('COMERCIAL', 'COMERCIAL'), ('RESIDDENCIAL', 'RESIDENCIAL')], default='RESIDDENCIAL', max_length=2),
        ),
    ]
