# Generated by Django 2.1.1 on 2019-02-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0007_auto_20190210_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='tipo_endereco',
            field=models.CharField(choices=[('C', 'COMERCIAL'), ('R', 'RESIDENCIAL')], default='R', max_length=2),
        ),
    ]
