# Generated by Django 2.1.1 on 2019-02-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('proxima', models.DateField()),
                ('is_anual', models.BooleanField(default=False, verbose_name='Anual')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('pertence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animal.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='TiposServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.TiposServico'),
        ),
    ]
