# Generated by Django 2.1.1 on 2019-02-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20190217_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='id_animal',
            new_name='animal',
        ),
    ]
