# Generated by Django 2.1.1 on 2019-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_auto_20190217_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='proxima',
            field=models.DateField(blank=True, null=True),
        ),
    ]
