# Generated by Django 2.1.1 on 2019-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
    ]
