# Generated by Django 2.1.1 on 2019-01-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('clientes', '0003_auto_20190119_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ManyToManyField(to='enderecos.Endereco'),
        ),
    ]
