# Generated by Django 2.1.1 on 2019-01-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
    ]
