# Generated by Django 2.1.1 on 2019-02-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20190210_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='comercial',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
