# Generated by Django 2.1.1 on 2019-02-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=100)),
                ('tipo_contato', models.CharField(choices=[('CELULAR', 'CELULAR'), ('TELEFONE RESIDENCIAL', 'TELEFONE RESIDENCIAL'), ('TELEFONE COMERCIAL', 'TELEFONE COMERCIAL'), ('EMAIL', 'EMAIL')], default='CELULAR', max_length=40)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('pertence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
        ),
    ]
