# Generated by Django 2.1.1 on 2019-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tipo_contato',
            field=models.CharField(choices=[('CELULAR', 'CELULAR'), ('TELEFONE RESIDENCIAL', 'TELEFONE RESIDENCIAL'), ('TELEFONE COMERCIAL', 'TELEFONE COMERCIAL'), ('EMAIL', 'EMAIL')], default='CELULAR', max_length=40),
        ),
    ]
