# Generated by Django 2.1.1 on 2019-02-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('racas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'MACHO'), ('F', 'FEMEA')], default='M', max_length=2)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('pertence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='racas.Raca')),
            ],
        ),
    ]
