# Generated by Django 2.1.1 on 2019-01-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_especie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='especie',
        ),
    ]
