# Generated by Django 2.1.1 on 2019-01-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0002_auto_20190119_1736'),
        ('animal', '0003_remove_animal_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='especies.Especie'),
            preserve_default=False,
        ),
    ]
