# Generated by Django 2.1.1 on 2019-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_animal_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='M', max_length=2),
        ),
    ]
