# Generated by Django 2.1.1 on 2019-02-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racas', '0001_initial'),
        ('animal', '0006_auto_20190210_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='especie',
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='racas.Raca'),
            preserve_default=False,
        ),
    ]
