# Generated by Django 2.1.1 on 2019-02-11 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_auto_20190211_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='date_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AddField(
            model_name='animal',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
